server:
  port: 8088


#Person:
#  lastName: zhangsan
#  age: 18
#  boss: false
#  birth: 2021/05/15
#  maps: {k1: v1,k2: v2}
#  lists:
#    - lisi
#    - wangwu
#    - zhaoliu
#  dog:
#    name: 小黄
#    age: 2